name: simplelogger Release

on:
  push:
    branches: [ main ]

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      published: ${{ steps.semantic.outputs.new_release_published }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19
          branch: main
          extends: |
            semantic-release-monorepo
          working_directory: ./simplelogger
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/changelog@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}

